sudo: required
services:
  - docker

script:
  - make build
  - docker images

after_success:
  - echo "TRAVIS_PULL_REQUEST_BRANCH => ${TRAVIS_PULL_REQUEST_BRANCH}"
  - echo "TRAVIS_BRANCH => ${TRAVIS_BRANCH}"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker images
  - make tag
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      make push;
    else
      echo "skipping docker push for ${TRAVIS_BRANCH}";
    fi;
