sudo: required
services:
  - docker

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - make build
        - docker images
    - stage: deploy
      if: branch = master
      install: skip
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker images
        - make tag
        - make push
