sudo: required
services:
  - docker

script:
  - make build
  - docker images

jobs:
include:
  - stage: deploy
    if: branch = master
    install: skip
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker images
    - make tag
    - make push
