sudo: required
services:
  - docker

script:
  - make build
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker images
  - make tag
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then \
        make push; \
      else \
        echo "skipping push for ${TRAVIS_BRANCH}"; \
      fi;
